import type { ChipCategoryItem } from '@/types';

export const ChipCategoryItems: ChipCategoryItem[] = [
  { name: 'All' },
  { name: 'Music' },
  { name: 'Games' },
  { name: 'News' },
  { name: 'Live' },
  { name: 'Sports' },
  { name: 'Fashion' },
  { name: 'Learning' },
  { name: 'Technology' },
  { name: 'Movies' },
  { name: 'Comedy' },
  { name: 'Education' },
  { name: 'Vlogs' },
  { name: 'DIY' },
  { name: 'Fitness' },
  { name: 'Travel' },
  { name: 'Science' },
  { name: 'Motivation' },
  { name: 'Anime' },
  { name: 'Podcasts' },
  { name: 'History' },
  { name: 'Cooking' },
  { name: 'Art' },
  { name: 'Books' },
  { name: 'Programming' },
  { name: 'Startups' },
  { name: 'Design' },
  { name: 'Finance' },
  { name: 'Marketing' },
  { name: 'Photography' },
  { name: 'Languages' },
];