import { YouTubeVideo } from "@/types";

export const youtubeData: YouTubeVideo[] = [
    {
        "id": "1",
        "title": "Big Buck Bunny",
        "thumbnailUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Big_Buck_Bunny_thumbnail_vlc.png/1200px-Big_Buck_Bunny_thumbnail_vlc.png",
        "duration": "8:18",
        "uploadTime": "May 9, 2011",
        "views": "24,969,123",
        "author": "Vlc Media Player",
        "authorAvatar": "https://yt3.ggpht.com/j4winp9JW48bX0r_7zbcZKEG-LQ2vg2aTqp2QPQxL7E2am5Iyqw3CR1cAmdjHWdiJms2b1AS=s68-c-k-c0x00ffffff-no-rj",
        "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "description": "Big Buck Bunny tells the story of a giant rabbit with a heart bigger than himself. When one sunny day three rodents rudely harass him, something snaps... and the rabbit ain't no bunny anymore! In the typical cartoon tradition he prepares the nasty rodents a comical revenge.\n\nLicensed under the Creative Commons Attribution license\nhttp://www.bigbuckbunny.org",
        "subscriber": "25,254,545 Subscribers",
        "isLive": true
    },
    {
        "id": "2",
        "title": "The first Blender Open Movie from 2006", 
        "thumbnailUrl": "https://i.ytimg.com/vi_webp/gWw23EYM9VM/maxresdefault.webp",
        "duration": "12:18",
        "uploadTime": "May 9, 2011",
        "views": "24,969,123",
        "author": "Blender Inc.",
        "authorAvatar": "https://yt3.ggpht.com/j4winp9JW48bX0r_7zbcZKEG-LQ2vg2aTqp2QPQxL7E2am5Iyqw3CR1cAmdjHWdiJms2b1AS=s68-c-k-c0x00ffffff-no-rj",
        "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "description": "The first Blender Open Movie from 2006, Elephants Dream, tells the story of two strange characters exploring a surreal mechanical world. It was the first open movie project by the Blender Foundation.", // Updated description
        "subscriber": "10,500,000 Subscribers",
        "isLive": true
    },
    {
        "id": "3",
        "title": "For Bigger Blazes",
        "thumbnailUrl": "https://i.ytimg.com/vi/Dr9C2oswZfA/maxresdefault.jpg",
        "duration": "0:15", 
        "uploadTime": "Apr 21, 2014", 
        "views": "1,088,574",
        "author": "Google Chromecast",
        "authorAvatar": "https://yt3.ggpht.com/j4winp9JW48bX0r_7zbcZKEG-LQ2vg2aTqp2QPQxL7E2am5Iyqw3CR1cAmdjHWdiJms2b1AS=s68-c-k-c0x00ffffff-no-rj",
        "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        "description": "Introducing Chromecast. The easiest way to enjoy online video and music on your TV. For $35.  Learn how to use Chromecast with Google Play Movies and more at google.com/chromecast.", // Updated description
        "subscriber": "5,340,000 Subscribers",
        "isLive": true
    },
    {
        "id": "4",
        "title": "For Bigger Escape",
        "thumbnailUrl": "https://img.jakpost.net/c/2019/09/03/2019_09_03_78912_1567484272._large.jpg",
        "duration": "0:15",
        "uploadTime": "Apr 21, 2014", 
        "views": "987,654",
        "author": "Google Chromecast",
        "authorAvatar": "https://yt3.ggpht.com/j4winp9JW48bX0r_7zbcZKEG-LQ2vg2aTqp2QPQxL7E2am5Iyqw3CR1cAmdjHWdiJms2b1AS=s68-c-k-c0x00ffffff-no-rj",
        "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        "description": "Introducing Chromecast. The easiest way to enjoy online video and music on your TV—for when Batman's escapes aren't quite big enough. For $35. Learn how to use Chromecast with Google Play Movies and more at google.com/chromecast.",
        "subscriber": "5,340,000 Subscribers",
        "isLive": false
    },
    {
        "id": "5",
        "title": "Big Buck Bunny (Duplicate Entry Example)", 
        "thumbnailUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Big_Buck_Bunny_thumbnail_vlc.png/1200px-Big_Buck_Bunny_thumbnail_vlc.png",
        "duration": "8:18",
        "uploadTime": "May 10, 2011", 
        "views": "15,000,000",
        "author": "Vlc Media Player",
        "authorAvatar": "https://yt3.ggpht.com/j4winp9JW48bX0r_7zbcZKEG-LQ2vg2aTqp2QPQxL7E2am5Iyqw3CR1cAmdjHWdiJms2b1AS=s68-c-k-c0x00ffffff-no-rj",
        "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "description": "A re-upload of the classic Big Buck Bunny. Enjoy the adventures of the giant rabbit once more!",
        "subscriber": "25,254,545 Subscribers",
        "isLive": true
    },
    {
        "id": "6",
        "title": "For Bigger Joyrides", 
        "thumbnailUrl": "https://i.ytimg.com/vi/Dr9C2oswZfA/maxresdefault.jpg", 
        "duration": "0:15", 
        "uploadTime": "Apr 21, 2014",
        "views": "850,320",
        "author": "Google Chromecast",
        "authorAvatar": "https://yt3.ggpht.com/j4winp9JW48bX0r_7zbcZKEG-LQ2vg2aTqp2QPQxL7E2am5Iyqw3CR1cAmdjHWdiJms2b1AS=s68-c-k-c0x00ffffff-no-rj",
        "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
        "description": "Chromecast: For bigger joyrides. The easiest way to enjoy online video and music on your TV. For $35.",
        "subscriber": "5,340,000 Subscribers",
        "isLive": false
    },
    {
        "id": "7",
        "title": "For Bigger Meltdowns",
        "thumbnailUrl": "https://img.jakpost.net/c/2019/09/03/2019_09_03_78912_1567484272._large.jpg",
        "duration": "0:15",
        "uploadTime": "Apr 21, 2014",
        "views": "730,110",
        "author": "Google Chromecast",
        "authorAvatar": "https://yt3.ggpht.com/j4winp9JW48bX0r_7zbcZKEG-LQ2vg2aTqp2QPQxL7E2am5Iyqw3CR1cAmdjHWdiJms2b1AS=s68-c-k-c0x00ffffff-no-rj",
        "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
        "description": "Chromecast: For bigger meltdowns. The easiest way to enjoy online video and music on your TV. For $35.",
        "subscriber": "5,340,000 Subscribers",
        "isLive": true
    },
    {
        "id": "8",
        "title": "Sintel - Third Blender Open Movie", 
        "thumbnailUrl": "https://i.ytimg.com/vi_webp/gWw23EYM9VM/maxresdefault.webp",
        "duration": "14:48",
        "uploadTime": "Sep 27, 2010", 
        "views": "12,345,678",
        "author": "Blender Foundation",
        "authorAvatar": "https://yt3.ggpht.com/j4winp9JW48bX0r_7zbcZKEG-LQ2vg2aTqp2QPQxL7E2am5Iyqw3CR1cAmdjHWdiJms2b1AS=s68-c-k-c0x00ffffff-no-rj",
        "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "description": "Sintel is an independently produced short film, initiated by the Blender Foundation as a means to further improve and validate the free/open source 3D creation suite Blender.",
        "subscriber": "10,500,000 Subscribers",
        "isLive": false
    },
    {
        "id": "9",
        "title": "Subaru Outback On Street And Dirt",
        "thumbnailUrl": "https://i.ytimg.com/vi_webp/gWw23EYM9VM/maxresdefault.webp", 
        "duration": "2:41",
        "uploadTime": "Feb 13, 2013",
        "views": "450,789",
        "author": "Subaru",
        "authorAvatar": "https://yt3.ggpht.com/j4winp9JW48bX0r_7zbcZKEG-LQ2vg2aTqp2QPQxL7E2am5Iyqw3CR1cAmdjHWdiJms2b1AS=s68-c-k-c0x00ffffff-no-rj",
        "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
        "description": "The Subaru Outback. Is it a car? Is it an SUV? Or is it something altogether different? It’s the Best of Both. Or is it? Test it out on the street, or take it for a spin on the dirt. ",
        "subscriber": "1,200,000 Subscribers",
        "isLive": false
    },
    {
        "id": "10",
        "title": "Tears of Steel - Fourth Blender Open Movie",
        "thumbnailUrl": "https://i.ytimg.com/vi_webp/gWw23EYM9VM/maxresdefault.webp", 
        "duration": "12:14",
        "uploadTime": "Sep 26, 2012",
        "views": "9,876,543",
        "author": "Blender Foundation",
        "authorAvatar": "https://yt3.ggpht.com/j4winp9JW48bX0r_7zbcZKEG-LQ2vg2aTqp2QPQxL7E2am5Iyqw3CR1cAmdjHWdiJms2b1AS=s68-c-k-c0x00ffffff-no-rj",
        "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "description": "Tears of Steel was realized with crowd-funding by users of the open source 3D creation tool Blender. Target was to improve and test a complete open and free pipeline for visual effects in film - and to make a compelling Sci-Fi film in Amsterdam, the Netherlands.",
        "subscriber": "10,500,000 Subscribers",
        "isLive": false
    },
    {
        "id": "11",
        "title": "Volkswagen GTI Review",
        "thumbnailUrl": "https://i.ytimg.com/vi_webp/gWw23EYM9VM/maxresdefault.webp", 
        "duration": "2:40",
        "uploadTime": "Feb 13, 2013",
        "views": "2,345,678",
        "author": "Volkswagen",
        "authorAvatar": "https://yt3.ggpht.com/j4winp9JW48bX0r_7zbcZKEG-LQ2vg2aTqp2QPQxL7E2am5Iyqw3CR1cAmdjHWdiJms2b1AS=s68-c-k-c0x00ffffff-no-rj",
        "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
        "description": "The Smoking Tire heads out to Adams Motorsports Park in Riverside, CA to test out the all-new Volkswagen GTI. In German, GTI stands for “Gran Tourismo Injection.”",
        "subscriber": "3,000,000 Subscribers",
        "isLive": false
    },
    {
        "id": "12",
        "title": "We Are Going On Bullrun",
        "thumbnailUrl": "https://i.ytimg.com/vi_webp/gWw23EYM9VM/maxresdefault.webp", 
        "duration": "2:03",
        "uploadTime": "Feb 13, 2013",
        "views": "999,999",
        "author": "The Smoking Tire",
        "authorAvatar": "https://yt3.ggpht.com/j4winp9JW48bX0r_7zbcZKEG-LQ2vg2aTqp2QPQxL7E2am5Iyqw3CR1cAmdjHWdiJms2b1AS=s68-c-k-c0x00ffffff-no-rj",
        "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
        "description": "The Smoking Tire is going on the 2010 Bullrun Rally in a 2011 Shelby GT500, and posting a video from the road every single day! Follow along with us July 10th-16th.",
        "subscriber": "1,500,000 Subscribers",
        "isLive": false
    },

    {
        "id": "13",
        "title": "Learn TypeScript in 1 Hour",
        "thumbnailUrl": "https://i.ytimg.com/vi/gWw23EYM9VM/maxresdefault.webp",
        "duration": "58:30",
        "uploadTime": "Jan 15, 2024",
        "views": "1,250,870",
        "author": "CodeMasterPro",
        "authorAvatar": "https://yt3.ggpht.com/j4winp9JW48bX0r_7zbcZKEG-LQ2vg2aTqp2QPQxL7E2am5Iyqw3CR1cAmdjHWdiJms2b1AS=s68-c-k-c0x00ffffff-no-rj",
        "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", 
        "description": "A comprehensive tutorial to learn TypeScript from scratch. Covers all the basics and advanced concepts to get you started.",
        "subscriber": "750K Subscribers",
        "isLive": false
    },
    {
        "id": "14",
        "title": "Tropical Chill - Relaxing Music Mix",
        "thumbnailUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Big_Buck_Bunny_thumbnail_vlc.png/1200px-Big_Buck_Bunny_thumbnail_vlc.png", 
        "duration": "2:30:45",
        "uploadTime": "Jul 2, 2023",
        "views": "10,500,321",
        "author": "ChillVibesOnly",
        "authorAvatar": "https://yt3.ggpht.com/j4winp9JW48bX0r_7zbcZKEG-LQ2vg2aTqp2QPQxL7E2am5Iyqw3CR1cAmdjHWdiJms2b1AS=s68-c-k-c0x00ffffff-no-rj",
        "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "description": "The perfect background music for studying, relaxing, or just chilling. Enjoy these tropical beats!",
        "subscriber": "1.2M Subscribers",
        "isLive": false
    },
    {
        "id": "15",
        "title": "🔴 LIVE: Pro Gamer Finals - Epic Showdown!",
        "thumbnailUrl": "https://i.ytimg.com/vi/Dr9C2oswZfA/maxresdefault.jpg",
        "duration": "LIVE",
        "uploadTime": "Streaming now", 
        "views": "25,670 watching",
        "author": "eSports Central",
        "authorAvatar": "https://yt3.ggpht.com/j4winp9JW48bX0r_7zbcZKEG-LQ2vg2aTqp2QPQxL7E2am5Iyqw3CR1cAmdjHWdiJms2b1AS=s68-c-k-c0x00ffffff-no-rj",
        "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4", 
        "description": "Join us live for the grand finals! Who will take home the trophy? Chat with other fans and enjoy the action!",
        "subscriber": "2.5M Subscribers",
        "isLive": true
    },
    {
        "id": "16",
        "title": "The Wonders of the Cosmos: A Space Documentary",
        "thumbnailUrl": "https://img.jakpost.net/c/2019/09/03/2019_09_03_78912_1567484272._large.jpg", 
        "duration": "45:10",
        "uploadTime": "Mar 10, 2022",
        "views": "5,678,901",
        "author": "CosmicVoyager",
        "authorAvatar": "https://yt3.ggpht.com/j4winp9JW48bX0r_7zbcZKEG-LQ2vg2aTqp2QPQxL7E2am5Iyqw3CR1cAmdjHWdiJms2b1AS=s68-c-k-c0x00ffffff-no-rj",
        "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4", 
        "description": "Explore the vastness of space, from distant galaxies to mysterious black holes. A journey through the wonders of our universe.",
        "subscriber": "3M Subscribers",
        "isLive": false
    },
    {
        "id": "17",
        "title": "Funny Pet Moments Compilation #23",
        "thumbnailUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Big_Buck_Bunny_thumbnail_vlc.png/1200px-Big_Buck_Bunny_thumbnail_vlc.png", 
        "duration": "10:05",
        "uploadTime": "Sep 5, 2023",
        "views": "750,123",
        "author": "PetLife",
        "authorAvatar": "https://yt3.ggpht.com/j4winp9JW48bX0r_7zbcZKEG-LQ2vg2aTqp2QPQxL7E2am5Iyqw3CR1cAmdjHWdiJms2b1AS=s68-c-k-c0x00ffffff-no-rj",
        "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", 
        "description": "Get ready to laugh! Here are some of the funniest pet moments caught on camera. You won't be able to stop smiling.",
        "subscriber": "900K Subscribers",
        "isLive": false
    }
];